### ISSUE TITLE
Create table for the first template

### ISSUE THREAD

**Issue by bernardarhia** [bernardarhia/portfolio-project#2]
You are to create the table for the first template as soon as possible.
model name should be  **TEMPLATES**

- [ ] Create table for template

// first object is the stylings for the template
  {
  templateNumber: 1,
  introText: {
    text: {
      word: "",
    },
    style: {
      color: "",
      fontSize: "",
      fontWeight: "",
      fontFamily: "",
      paddingX: "",
      paddingY: "",
      letterSpacing: "",
      lineHeight: "",
    },
  },
  paragraphText: {
    text: {
      word: "",
    },
    style: {
      color: "",
      fontSize: "",
      fontWeight: "",
      fontFamily: "",
      paddingX: "",
      paddingY: "",
      letterSpacing: "",
      lineHeight: "",
    },
  },
  templateImage: {
    url: "",
    style: {
      borderRadius: "",
    },
  },
  buttonLeft: {
    backgroundColor: "",
    fontSize: "",
    color: "",
    width: "",
    height: "",
    padding: "",
  },
  buttonRight: {
    backgroundColor: "",
    fontSize: "",
    color: "",
    width: "",
    height: "",
    padding: "",
  },
  socialLinks: {
    github: "",
    twitter: "",
    linkedin: "",
    email: "",
    blog: "",
  },

  project: [
    {
      projectImage: "",
      projectTitle: "",
      projectUrl: "",
      projectDescription: "",
    },
  ],
  skills:[
      {
          skillName:'',
          skillPng:'',
      }
  ],
  resumeFile:''
};

- [ ] Auto-add template to user table when a user registers for the first time 

### The endpoints
- [ ] POST /users/template/add ----- creates the virtual template column in the user table (This will have the same structure as the first template table)
- [ ]  GET /users/template  ----- fetches the template the user has in its table
- [ ] PUT /users/template/edit_template ----- edit/update the template
- [ ] DELETE /users/template/delete_template ----- deletes the virtual template column in the user table

### Note:
 _All template endpoints are to return the template object in the user table without the **ids**_

**Comment by zaidanali028** [comment]
table?as in the database schema?

**Comment by bernardarhia** [comment]
yes, please. I might add a few columns to it for you to update it later but fo now create the schema provided

**Comment by bernardarhia** [comment]
And please check the tasks you complete so we can all know your process. I will do the same on my task

**Comment by zaidanali028** [comment]
https://github.com/zaidanali028/portfolio-project
updated
